### ISSUE TITLE
lede编译出现错误

### ISSUE THREAD

**Issue by wclmgcd** [douglarek/luci-app-homeproxy#18]
大雕的源是Firewall ，而homeproxy 是Firewall4，选择homeproxy 自动勾选Firewall4，但Firewall及其依赖还是存在，所以编译时出现错误，怎么修改默认firewall为firewall4？

**Comment by douglarek** [comment]
这个可能需要去 LEDE 项目问了，这对使用 fw4 的应用都有类似的问题，应该不光 hp 有，鉴于我并不使用 LEDE，所以爱莫能助。
