### ISSUE TITLE
homeproxy的管理面板未出现在“菜单栏 -> 服务”中

### ISSUE THREAD

**Issue by bigoovip** [douglarek/luci-app-homeproxy#24]
在安装好luci-app-homeproxy后，刷新 LUCI 页面，在“菜单栏 -> 服务”中没有HomeProxy选项，通过刷新缓存（rm /tmp/luci-indexcache）并重启后也没有该选项。
下图是安装的版本。
![image](https://github.com/douglarek/luci-app-homeproxy/assets/86590318/e0bd8305-a663-4979-bd5e-10351c727b8e)

请教，该问题应如何解决？

**Comment by douglarek** [comment]
退出重新登录试试。

**Comment by bigoovip** [comment]
> 退出重新登录试试。

谢谢，已试过，退出重新登录没有作用，仍然没有homeproxy的管理面板。

**Comment by douglarek** [comment]
> > 退出重新登录试试。
> 
> 谢谢，已试过，退出重新登录没有作用，仍然没有homeproxy的管理面板。

用的什么固件。另外我仔细看了你的截图，这也不是我这个仓库的版本啊。从这里下载安装：https://github.com/douglarek/luci-app-homeproxy/releases 。

**Comment by bigoovip** [comment]
> > > 退出重新登录试试。
> > 
> > 
> > 谢谢，已试过，退出重新登录没有作用，仍然没有homeproxy的管理面板。
> 
> 用的什么固件。另外我仔细看了你的截图，这也不是我这个仓库的版本啊。从这里下载安装：https://github.com/douglarek/luci-app-homeproxy/releases 。

固件是lean的openwrt仓库自编译，homeproxy用的是本项目的仓库同步编译的。
以下为固件和内核版本。
![image](https://github.com/douglarek/luci-app-homeproxy/assets/86590318/1fb2a109-e389-4a2d-830f-2842c137a74f)

**Comment by douglarek** [comment]
> > > > 退出重新登录试试。
> > > 
> > > 
> > > 谢谢，已试过，退出重新登录没有作用，仍然没有homeproxy的管理面板。
> > 
> > 
> > 用的什么固件。另外我仔细看了你的截图，这也不是我这个仓库的版本啊。从这里下载安装：https://github.com/douglarek/luci-app-homeproxy/releases 。
> 
> 固件是lean的openwrt仓库自编译，homeproxy用的是本项目的仓库同步编译的。 以下为固件和内核版本。 ![image](https://user-images.githubusercontent.com/86590318/280581677-1fb2a109-e389-4a2d-830f-2842c137a74f.png)

如果不通过 openwrt 编译，直接通过我上面给出的链接下载使用 opkg 安装呢。

**Comment by bigoovip** [comment]
移除自编译版本，重新安装仓库发布版本release-2023110502，仍然没有管理页面。
![image](https://github.com/douglarek/luci-app-homeproxy/assets/86590318/2658a6a0-7de1-43c3-99af-af461931cc9f)

**Comment by douglarek** [comment]
> 移除自编译版本，重新安装仓库发布版本release-2023110502，仍然没有管理页面。 ![image](https://user-images.githubusercontent.com/86590318/280583795-2658a6a0-7de1-43c3-99af-af461931cc9f.png)

我自己不用 Lean，所以不太清楚具体什么状况。尝试过重启机器吗

**Comment by bigoovip** [comment]
> > 移除自编译版本，重新安装仓库发布版本release-2023110502，仍然没有管理页面。 ![image](https://user-images.githubusercontent.com/86590318/280583795-2658a6a0-7de1-43c3-99af-af461931cc9f.png)
> 
> 我自己不用 Lean，所以不太清楚具体什么状况。尝试过重启机器吗

试过重启openwrt，重启使用的PC，包括换浏览器，换其它PC登陆，全都不显示管理页面。
查过openwrt的系统日志，没有homeproxy的相关内容。

**以下为homeproxy的安装内容**：
![image](https://github.com/douglarek/luci-app-homeproxy/assets/86590318/c3bd1108-cf1c-45d0-948c-9743f54d1ecb)

**以下为/etc/config/homeproxy的内容：**

config homeproxy 'infra'
	option __warning 'DO NOT EDIT THIS SECTION, OR YOU ARE ON YOUR OWN!'
	option common_port '22,53,80,143,443,465,853,993,995,8080,8443,9418'
	option redirect_port '5331'
	option tproxy_port '5332'
	option dns_port '5333'
	option china_dns_port '5334'
	option tun_name 'singtun0'
	option tun_addr4 '172.19.0.1/30'
	option tun_addr6 'fdfe:dcba:9876::1/126'
	option tun_mtu '9000'
	option table_mark '100'
	option self_mark '100'
	option tproxy_mark '101'
	option tun_mark '102'

config homeproxy 'config'
	option clash_dashboard_port '9090'
	option main_node 'nil'
	option main_udp_node 'same'
	option dns_server '8.8.8.8'
	option routing_mode 'bypass_mainland_china'
	option routing_port 'common'
	option proxy_mode 'redirect_tproxy'
	option ipv6_support '1'

config homeproxy 'control'
	option lan_proxy_mode 'disabled'
	list wan_proxy_ipv4_ips '91.108.4.0/22'
	list wan_proxy_ipv4_ips '91.108.8.0/22'
	list wan_proxy_ipv4_ips '91.108.12.0/22'
	list wan_proxy_ipv4_ips '91.108.56.0/22'
	list wan_proxy_ipv4_ips '95.161.64.0/20'
	list wan_proxy_ipv4_ips '149.154.160.0/22'
	list wan_proxy_ipv4_ips '149.154.164.0/22'
	list wan_proxy_ipv4_ips '149.154.172.0/22'

config homeproxy 'routing'
	option sniff_override '1'
	option default_outbound 'direct-out'

config homeproxy 'dns'
	option dns_strategy 'prefer_ipv4'
	option default_server 'local-dns'
	option disable_cache '0'
	option disable_cache_expire '0'

config homeproxy 'subscription'
	option auto_update '0'
	option allow_insecure '0'
	option packet_encoding 'xudp'
	option update_via_proxy '0'
	option filter_nodes 'disabled'

config homeproxy 'server'
	option enabled '0'
	option auto_firewall '0'

**Comment by bigoovip** [comment]
> > 移除自编译版本，重新安装仓库发布版本release-2023110502，仍然没有管理页面。 ![image](https://user-images.githubusercontent.com/86590318/280583795-2658a6a0-7de1-43c3-99af-af461931cc9f.png)
> 
> 我自己不用 Lean，所以不太清楚具体什么状况。尝试过重启机器吗

请教下，您用的是啊个openwrt版本?

**Comment by douglarek** [comment]
> > > 移除自编译版本，重新安装仓库发布版本release-2023110502，仍然没有管理页面。 ![image](https://user-images.githubusercontent.com/86590318/280583795-2658a6a0-7de1-43c3-99af-af461931cc9f.png)
> > 
> > 
> > 我自己不用 Lean，所以不太清楚具体什么状况。尝试过重启机器吗
> 
> 请教下，您用的是啊个openwrt版本?

immortalwrt

**Comment by douglarek** [comment]
> > > 移除自编译版本，重新安装仓库发布版本release-2023110502，仍然没有管理页面。 ![image](https://user-images.githubusercontent.com/86590318/280583795-2658a6a0-7de1-43c3-99af-af461931cc9f.png)
> > 
> > 
> > 我自己不用 Lean，所以不太清楚具体什么状况。尝试过重启机器吗
> 
> 试过重启openwrt，重启使用的PC，包括换浏览器，换其它PC登陆，全都不显示管理页面。 查过openwrt的系统日志，没有homeproxy的相关内容。
> 
> **以下为homeproxy的安装内容**： ![image](https://user-images.githubusercontent.com/86590318/280587010-c3bd1108-cf1c-45d0-948c-9743f54d1ecb.png)
> 
> **以下为/etc/config/homeproxy的内容：**
> 
> config homeproxy 'infra' option __warning 'DO NOT EDIT THIS SECTION, OR YOU ARE ON YOUR OWN!' option common_port '22,53,80,143,443,465,853,993,995,8080,8443,9418' option redirect_port '5331' option tproxy_port '5332' option dns_port '5333' option china_dns_port '5334' option tun_name 'singtun0' option tun_addr4 '172.19.0.1/30' option tun_addr6 'fdfe:dcba:9876::1/126' option tun_mtu '9000' option table_mark '100' option self_mark '100' option tproxy_mark '101' option tun_mark '102'
> 
> config homeproxy 'config' option clash_dashboard_port '9090' option main_node 'nil' option main_udp_node 'same' option dns_server '8.8.8.8' option routing_mode 'bypass_mainland_china' option routing_port 'common' option proxy_mode 'redirect_tproxy' option ipv6_support '1'
> 
> config homeproxy 'control' option lan_proxy_mode 'disabled' list wan_proxy_ipv4_ips '91.108.4.0/22' list wan_proxy_ipv4_ips '91.108.8.0/22' list wan_proxy_ipv4_ips '91.108.12.0/22' list wan_proxy_ipv4_ips '91.108.56.0/22' list wan_proxy_ipv4_ips '95.161.64.0/20' list wan_proxy_ipv4_ips '149.154.160.0/22' list wan_proxy_ipv4_ips '149.154.164.0/22' list wan_proxy_ipv4_ips '149.154.172.0/22'
> 
> config homeproxy 'routing' option sniff_override '1' option default_outbound 'direct-out'
> 
> config homeproxy 'dns' option dns_strategy 'prefer_ipv4' option default_server 'local-dns' option disable_cache '0' option disable_cache_expire '0'
> 
> config homeproxy 'subscription' option auto_update '0' option allow_insecure '0' option packet_encoding 'xudp' option update_via_proxy '0' option filter_nodes 'disabled'
> 
> config homeproxy 'server' option enabled '0' option auto_firewall '0'

下面这个是我的 `find / -name homeproxy` 输出：

```
/etc/config/homeproxy
/etc/homeproxy
/etc/init.d/homeproxy
/overlay/upper/etc/config/homeproxy
/overlay/upper/etc/homeproxy
/overlay/upper/etc/init.d/homeproxy
/overlay/upper/www/luci-static/resources/view/homeproxy
/rom/etc/config/homeproxy
/rom/etc/homeproxy
/rom/etc/init.d/homeproxy
/rom/www/luci-static/resources/view/homeproxy
/sys/fs/cgroup/services/homeproxy
/tmp/.uci/homeproxy
/tmp/run/homeproxy
/tmp/run/rpcd/uci-6392f8fb9aa3f65ed33cd6c50da80621/homeproxy
/www/luci-static/resources/view/homeproxy
```

**Comment by douglarek** [comment]
如果你动手能力强，可以试着编译一下 imm 看是否有问题，这个是原版 hp：https://github.com/immortalwrt/luci/tree/master/applications/luci-app-homeproxy 。

**Comment by bigoovip** [comment]
> 如果你动手能力强，可以试着编译一下 imm 看是否有问题，这个是原版 hp：https://github.com/immortalwrt/luci/tree/master/applications/luci-app-homeproxy 。

刚已试过在lean下编译了原版HP,还是没有管理页面，初步估计可能是lean版的默认防火墙是firewall，而hp要求的是firewall4，在lean编译文件中，虽然我更改为了firewall4，但可能还是有什么地方遗漏了，等我有空试试imm。

**Comment by bigoovip** [comment]
重新在imm中编译，编译成功并正确显示相关页面了。
