### ISSUE TITLE
【功能增强】能否增加直接导入自定义配置文件的功能

### ISSUE THREAD

**Issue by bigoovip** [douglarek/luci-app-homeproxy#25]
能否增加直接导入自定义配置文件的功能，项目的luci管理页面上路由节点|规则、DNS相关、节点组相关，都要一条条的设置，我有几万条相关的规则和节点组，真没办法一条条的添加。

**Comment by ghost** [comment]
强烈支持！比如可以搞个高级模式，如果用户导入配置就不显示ui设置也行。

**Comment by douglarek** [comment]
这个问题有可能在  sing-box 1.8 支持 rule-set 之后有所缓解。

**Comment by ghost** [comment]
但是 规则还是需要手动添加，如果能直接导入json配置就好了（哪怕这时候只剩下最简单的ui功能）。

**Comment by douglarek** [comment]
> 但是 规则还是需要手动添加，如果能直接导入json配置就好了（哪怕这时候只剩下最简单的ui功能）。

直接用  sing-box 即可。

**Comment by ghost** [comment]
sing-box 会自动添加防火墙设置么？

**Comment by douglarek** [comment]
> sing-box 会自动添加防火墙设置么？

自行去试。
