### ISSUE TITLE
homeproxy 自定义DNS

### ISSUE THREAD

**Issue by sdhz151** [douglarek/luci-app-homeproxy#35]
怎么设置让luci-app-homeproxy支持mosdns或smartdns的监听端口，如pa那样127.0.0.1:7913这样

**Comment by rannj** [comment]
服务器可以直接写127.0.0.1，然后dnsmasq那里”dns转发”写”127.0.0.1#7913"，也就是你dns服务器的监听端口，这样应该就可以了。
