### ISSUE TITLE
安装immortalwrt源的homeproxy可以使用，但是安装这里的ipk就不行

### ISSUE THREAD

**Issue by elric8** [douglarek/luci-app-homeproxy#36]
安装大佬您的改版的ipk发现少装了china-dns这个依赖
但是手动安装上去还是不能使用

都是dns报错+0000 2023-11-22 16:11:14 ERROR dns: exchange failed for accounts.google.com. IN HTTPS: CRYPTO_ERROR 0x12a (local): tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by douglarek** [comment]
本 fork 主打一个 自定义路由 模式（该模式并不依赖 china-dns），你可以试试这个模式（新版该模式将是唯一模式）。如果不用自定义模式，建议使用原版。另外，根据你的问题描述，我无法重现。
