### ISSUE TITLE
Hysteria2订阅错误，会变成SOCKS协议节点！

### ISSUE THREAD

**Issue by 598673A** [douglarek/luci-app-homeproxy#48]
Hysteria2订阅错误！订阅Hysteria2协议节点，会变成SOCKS协议节点，官方版本没有这个问题，可以正确识别Hysteria2节点！

**Comment by douglarek** [comment]
> Hysteria2订阅错误！订阅Hysteria2协议节点，会变成SOCKS协议节点，官方版本没有这个问题，可以正确识别Hysteria2节点！

你的 Hysteria2 订阅长啥样，给个样例看看。

**Comment by douglarek** [comment]
找到问题了，晚上修一下。

**Comment by douglarek** [comment]
Fixed in 4e910da541f99f3db6c604b7189ef76860e5e8d7. please try the latest release here: https://github.com/douglarek/luci-app-homeproxy/releases.

**Comment by 598673A** [comment]
重新编译了一下，没问题了，可以正常订阅hy2节点，大佬好有效率！感谢！
