### ISSUE TITLE
wireguard無法連

### ISSUE THREAD

**Issue by s920395** [douglarek/luci-app-homeproxy#53]
![01](https://github.com/douglarek/luci-app-homeproxy/assets/47146821/a9d64cbc-2560-4476-aa2b-9f8f8542363f)
![02](https://github.com/douglarek/luci-app-homeproxy/assets/47146821/42640095-b832-4034-9aaf-0488758da983)
![03](https://github.com/douglarek/luci-app-homeproxy/assets/47146821/06842b93-e19d-4849-821b-bc8a02ec37e9)
![04](https://github.com/douglarek/luci-app-homeproxy/assets/47146821/c56e535e-42b0-4a00-a176-47b3a068e96a)
![05](https://github.com/douglarek/luci-app-homeproxy/assets/47146821/56f4db31-6d98-4f8d-a616-6d4c11c75402)
![06](https://github.com/douglarek/luci-app-homeproxy/assets/47146821/1364e5f9-605b-4fda-bdac-9cfccf231bb0)
singbox 1.7.7無法連，先前的1.6.6是可以連的，homeproxy是用2024010900。
openwrt是23.05.2 x86-64

**Comment by douglarek** [comment]
> singbox 1.7.7無法連，先前的1.6.6是可以連的，homeproxy是用2024010900。 openwrt是23.05.2 x86-64

If your singbox version is lower than 1.8.0, please use a version prior to 2023123000.

**Comment by s920395** [comment]
換singbox 1.8.0後，homeproxy能正常運行，但wireguard還是無法連google。
singbox 1.8.0是來自https://github.com/xiaorouji/openwrt-passwall2/releases/download/1.22-2/passwall2_packages_ipk_x86_64.zip

**Comment by douglarek** [comment]
> 換singbox 1.8.0後，homeproxy能正常運行，但wireguard還是無法連google。 singbox 1.8.0是來自https://github.com/xiaorouji/openwrt-passwall2/releases/download/1.22-2/passwall2_packages_ipk_x86_64.zip

detail logs

**Comment by s920395** [comment]
![000](https://github.com/douglarek/luci-app-homeproxy/assets/47146821/32295a5c-0b8b-44b1-89ba-eeec6631baf4)

**Comment by douglarek** [comment]
> ![000](https://private-user-images.githubusercontent.com/47146821/295258563-32295a5c-0b8b-44b1-89ba-eeec6631baf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MTU2NTcsIm5iZiI6MTcwNDgxNTM1NywicGF0aCI6Ii80NzE0NjgyMS8yOTUyNTg1NjMtMzIyOTVhNWMtMGI4Yi00NGIxLTg5YmEtZWVlYzY2MzFiYWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE1NDkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZWI4OGUzYmIzYTQ4MzlkYTI4MmFhZGUwNTc2NTFjZjM1NTI0OTBlYTg5ODk5YzYzYWFlMTEwNTk2NzRkNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h7De-nvnrsIMFKQX-Wkkf7SVk5px42LfN2jko34WEfM)

offer sing-box-c.json

**Comment by s920395** [comment]
從哪個目錄提取?

**Comment by douglarek** [comment]
> 從哪個目錄提取?

/var/run/homeproxy

**Comment by s920395** [comment]
[sing-box-c.json](https://github.com/douglarek/luci-app-homeproxy/files/13876004/sing-box-c.json)

**Comment by s920395** [comment]
需要我私下提供1個設定檔讓你連看看嗎?

**Comment by douglarek** [comment]
> 需要我私下提供1個設定檔讓你連看看嗎?

你提供的 sing-box-c.json 我给你删了，以后不要上传自己的密钥配置，一定要脱敏。

你现在可以分两个方面确认：

1. 你的 wg 在 sing-box 其他的软件（android & ios）相同的参数（具体的参数在那个 sing-box-c.json）是否可以使用；
2. 提供一下 /var/run/homeproxy 下的 log 文件以及 openwrt 系统日志（非内核日志）中 sing-box 相关的日志，注意如有敏感信息一定要脱敏。

**Comment by s920395** [comment]
1.nekoray和nekobox都可以用
2.
[homeproxy.log](https://github.com/douglarek/luci-app-homeproxy/files/13883337/homeproxy.log)
Wed Jan 10 12:48:33 2024 daemon.notice procd: /etc/rc.d/S99sing-box: /etc/rc.common: line 39: iptables: not found
Wed Jan 10 12:48:33 2024 daemon.notice procd: /etc/rc.d/S99sing-box: sing-box is started!
Wed Jan 10 12:48:34 2024 daemon.err sing-box[2193]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Wed Jan 10 12:48:39 2024 daemon.err sing-box[2854]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Wed Jan 10 12:48:44 2024 daemon.err sing-box[3538]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Wed Jan 10 12:48:49 2024 daemon.err sing-box[3547]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Wed Jan 10 12:48:54 2024 daemon.err sing-box[3563]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Wed Jan 10 12:48:59 2024 daemon.err sing-box[3572]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Wed Jan 10 12:48:59 2024 daemon.info procd: Instance sing-box::instance1 s in a crash loop 6 crashes, 0 seconds since last crash

**Comment by douglarek** [comment]
> Wed Jan 10 12:48:33 2024 daemon.notice procd: /etc/rc.d/S99sing-box: /etc/rc.common: line 39: iptables: not found
> Wed Jan 10 12:48:33 2024 daemon.notice procd: /etc/rc.d/S99sing-box: sing-box is started!
> Wed Jan 10 12:48:34 2024 daemon.err sing-box[2193]: �[31mFATAL�[0m[0000] read config at ./config.json: open ./config.json: no such file or directory

你用的 openwrt 什么版本

**Comment by s920395** [comment]
23.0.5.2

**Comment by douglarek** [comment]
> Wed Jan 10 12:48:34 2024 daemon.err sing-box[2193]: �[31mFATAL�[0m[0000] read config at ./config.json: open ./config.json: no such file or directory

ps | grep sing-box 看看

**Comment by s920395** [comment]
> > Wed Jan 10 12:48:34 2024 daemon.err sing-box[2193]: �[31mFATAL�[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
> 
> ps | grep sing-box 看看

這是要在終端打指令嗎?

**Comment by douglarek** [comment]
> > > Wed Jan 10 12:48:34 2024 daemon.err sing-box[2193]: �[31mFATAL�[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
> > 
> > 
> > ps | grep sing-box 看看
> 
> 這是要在終端打指令嗎?

是的，另外确定你装 nftables 了吗

**Comment by douglarek** [comment]
> [homeproxy.log](https://github.com/douglarek/luci-app-homeproxy/files/13883337/homeproxy.log)
> Wed Jan 10 12:48:33 2024 daemon.notice procd: /etc/rc.d/S99sing-box: /etc/rc.common: line 39: iptables: not found
> Wed Jan 10 12:48:33 2024 daemon.notice procd: /etc/rc.d/S99sing-box: sing-box is started!
> Wed Jan 10 12:48:34 2024 daemon.err sing-box[2193]: �[31mFATAL�[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
> Wed Jan 10 12:48:39 2024 daemon.err sing-box[2854]: �[31mFATAL�[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
> Wed Jan 10 12:48:44 2024 daemon.err sing-box[3538]: �[31mFATAL�[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
> Wed Jan 10 12:48:49 2024 daemon.err sing-box[3547]: �[31mFATAL�[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
> Wed Jan 10 12:48:54 2024 daemon.err sing-box[3563]: �[31mFATAL�[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
> Wed Jan 10 12:48:59 2024 daemon.err sing-box[3572]: �[31mFATAL�[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
> Wed Jan 10 12:48:59 2024 daemon.info procd: Instance sing-box::instance1 s in a crash loop 6 crashes, 0 seconds since last crash

你的这个症状有两个：

1. iptables 找不到，理论上说你只能用 nftables，因为 hp 不支持 iptables，不确定你的 openwrt 是不是换皮 fw 3 的版本（非官方）；
2. sing-box 启动拿到的配置文件拿不到，你确定这是用 hp 启动的 sing-box 吗

**Comment by s920395** [comment]
![001](https://github.com/douglarek/luci-app-homeproxy/assets/47146821/08a40df1-e2be-4193-910f-6d344478ffd5)
是用hp啟動的沒錯
op我用官方的都是fw4

**Comment by s920395** [comment]
![002](https://github.com/douglarek/luci-app-homeproxy/assets/47146821/f7fbff77-9a8f-4015-9e58-0ff8a0dcec42)

**Comment by s920395** [comment]
我就只改介面其他都沒動了
luci-theme-argon
luci-app-argon-config

**Comment by douglarek** [comment]
> 是用hp啟動的沒錯

无法重现。

**Comment by douglarek** [comment]
I have closed it for now, if there are any other questions, feel free to reopen it.
