### ISSUE TITLE
什么时候支持节点测速和故障自动切换功能

### ISSUE THREAD

**Issue by ruchid123123** [douglarek/luci-app-homeproxy#55]
如题

**Comment by douglarek** [comment]
> 什么时候支持节点测速和故障自动切换功能

等你看明白 [wiki](https://github.com/douglarek/luci-app-homeproxy/wiki) 的时候。本 hp fork 支持 urltest 和 selector，虽然没有 fallback（问题是 sing-box 本身就不支持） 也可以勉强使用。
