### ISSUE TITLE
自行编译 luci-app-homeproxy 的几个问题

### ISSUE THREAD

**Issue by yukeiyang** [douglarek/luci-app-homeproxy#58]
**执行 `$ su - test` 后**

1, `$ sudo vi feeds.conf.default`  
编译时需要如下添加 feed 么？  
`src-git-full luci_app_homeproxy https://github.com/douglarek/luci-app-homeproxy`  

2, `$ make menuconfig`  
是选择 Applications 然后 Save 退出么？  

3, `$ make -V 99`  
是在 openwrt-sdk-23.05.2-x86-64_gcc-12.3.0_musl.Linux-x86_64 目录下直接执行该命令么？

**Comment by CHUNGPT17** [comment]
reate index file './feeds/luci_app_homeproxy.index' 
grep: feeds/luci_app_homeproxy/Makefile:#: No such file or directory
grep: call: No such file or directory
grep: BuildPackage: No such file or directory
grep: OpenWrt: No such file or directory
grep: buildroot: No such file or directory
grep: signature/Makefile: No such file or directory
/workspaces/codespaces-jupyter/openwrt/feeds/luci_app_homeproxy.tmp/info/.files-packageinfo.mk:1: *** target pattern contains no '%'.  Stop.

**Comment by douglarek** [comment]
Since you have reached the point where you can compile OpenWRT source code, a mere software issue should not be a problem for you. If necessary, you can refer to the OpenWRT documentation. However, this repository does not intend to address such issues, therefore this issue has been closed.
