### ISSUE TITLE
TUN mode cannot automatically start after restarting the device

### ISSUE THREAD

**Issue by ivanors** [douglarek/luci-app-homeproxy#61]
problem mode TUN cannot automatically start after restarting the device

![Screenshot 2024-01-21 233801](https://github.com/douglarek/luci-app-homeproxy/assets/81950468/abb30f2b-28b6-4edb-a7ff-4e6e2d06a4d8)

**Comment by douglarek** [comment]
> problem mode TUN cannot automatically start after restarting the device
> 
> ![Screenshot 2024-01-21 233801](https://private-user-images.githubusercontent.com/81950468/298397624-abb30f2b-28b6-4edb-a7ff-4e6e2d06a4d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTQ4OTMsIm5iZiI6MTcwNTg5NDU5MywicGF0aCI6Ii84MTk1MDQ2OC8yOTgzOTc2MjQtYWJiMzBmMmItMjhiNi00ZWRiLWE3ZmYtNGU2ZTJkMDZhNGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAzMzYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViODJlZTUxNmI4ZTM5YWU4ODA5ZmRhNWM1MTBmNGRhODJiMTMzM2E1Mjc5Y2VhOGUyY2Q4NGM4OGZiNjZhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rE3P0-4i-U6DgIrnU1B4IUv2QT-p0SWlqEUfcywA5b4)

is the original hp version ok ?

**Comment by ivanors** [comment]
I use the latest sing-box and the latest homeproxy on an openwrt 23.5 device experiencing the same problem in the previous version

**Comment by douglarek** [comment]
> I use the latest sing-box and the latest homeproxy on an openwrt 23.5 device experiencing the same problem in the previous version

Your question is very similar to the issue reported in the original HP repository. I am not an expert in this area, you can wait for the upstream fix or use tproxy as a workaround.

**Comment by douglarek** [comment]
The upstream has been repaired, and this repository has been synchronized.
